<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if(DB::table('countries')->get()->count() == 0)
        {
            //DB::table('countries')->truncate();

            $countries = [
                ['name' => 'Afghanistan', 'country_code' => 'AF', 'phonecode' => '93', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Åland Islands', 'country_code' => 'AX', 'phonecode' => '358', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Albania', 'country_code' => 'AL', 'phonecode' => '355', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Algeria', 'country_code' => 'DZ', 'phonecode' => '213', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'American Samoa', 'country_code' => 'AS', 'phonecode' => '1684', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Andorra', 'country_code' => 'AD', 'phonecode' => '376', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Angola', 'country_code' => 'AO', 'phonecode' => '244', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Anguilla', 'country_code' => 'AI', 'phonecode' => '1264', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Antarctica', 'country_code' => 'AQ', 'phonecode' => '0', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Antigua and Barbuda', 'country_code' => 'AG', 'phonecode' => '1268', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Argentina', 'country_code' => 'AR', 'phonecode' => '54', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Armenia', 'country_code' => 'AM', 'phonecode' => '374', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Aruba', 'country_code' => 'AW', 'phonecode' => '297', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Australia', 'country_code' => 'AU', 'phonecode' => '61', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Austria', 'country_code' => 'AT', 'phonecode' => '43', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Azerbaijan', 'country_code' => 'AZ', 'phonecode' => '994', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Bahamas', 'country_code' => 'BS', 'phonecode' => '1242', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Bahrain', 'country_code' => 'BH', 'phonecode' => '973', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Bangladesh', 'country_code' => 'BD', 'phonecode' => '880', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Barbados', 'country_code' => 'BB', 'phonecode' => '1246', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Belarus', 'country_code' => 'BY', 'phonecode' => '375', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Belgium', 'country_code' => 'BE', 'phonecode' => '32', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Belize', 'country_code' => 'BZ', 'phonecode' => '501', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Benin', 'country_code' => 'BJ', 'phonecode' => '229', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Bermuda', 'country_code' => 'BM', 'phonecode' => '1441', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Bhutan', 'country_code' => 'BT', 'phonecode' => '975', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Bolivia, Plurinational State of', 'country_code' => 'BO', 'phonecode' => '591', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Bonaire, Sint Eustatius and Saba', 'country_code' => 'BQ', 'phonecode' => '599', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Bosnia and Herzegovina', 'country_code' => 'BA', 'phonecode' => '387', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Botswana', 'country_code' => 'BW', 'phonecode' => '267', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Bouvet Island', 'country_code' => 'BV', 'phonecode' => '0', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Brazil', 'country_code' => 'BR', 'phonecode' => '55', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'British Indian Ocean Territory', 'country_code' => 'IO', 'phonecode' => '246', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Brunei Darussalam', 'country_code' => 'BN', 'phonecode' => '673', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Bulgaria', 'country_code' => 'BG', 'phonecode' => '359', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Burkina Faso', 'country_code' => 'BF', 'phonecode' => '226', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Burundi', 'country_code' => 'BI', 'phonecode' => '257', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Cambodia', 'country_code' => 'KH', 'phonecode' => '855', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Cameroon', 'country_code' => 'CM', 'phonecode' => '237', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Canada', 'country_code' => 'CA', 'phonecode' => '1', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Cape Verde', 'country_code' => 'CV', 'phonecode' => '238', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Cayman Islands', 'country_code' => 'KY', 'phonecode' => '1345', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Central African Republic', 'country_code' => 'CF', 'phonecode' => '236', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Chad', 'country_code' => 'TD', 'phonecode' => '235', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Chile', 'country_code' => 'CL', 'phonecode' => '56', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'China', 'country_code' => 'CN', 'phonecode' => '86', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Christmas Island', 'country_code' => 'CX', 'phonecode' => '61', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Cocos (Keeling) Islands', 'country_code' => 'CC', 'phonecode' => '672', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Colombia', 'country_code' => 'CO', 'phonecode' => '57', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Comoros', 'country_code' => 'KM', 'phonecode' => '269', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Congo', 'country_code' => 'CG', 'phonecode' => '242', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Congo, the Democratic Republic of the', 'country_code' => 'CD', 'phonecode' => '242', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Cook Islands', 'country_code' => 'CK', 'phonecode' => '682', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Costa Rica', 'country_code' => 'CR', 'phonecode' => '506', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Côte d\'Ivoire', 'country_code' => 'CI', 'phonecode' => '225', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Croatia', 'country_code' => 'HR', 'phonecode' => '385', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Cuba', 'country_code' => 'CU', 'phonecode' => '53', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Curaçao', 'country_code' => 'CW', 'phonecode' => '599', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Cyprus', 'country_code' => 'CY', 'phonecode' => '357', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Czech Republic', 'country_code' => 'CZ', 'phonecode' => '420', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Denmark', 'country_code' => 'DK', 'phonecode' => '45', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Djibouti', 'country_code' => 'DJ', 'phonecode' => '253', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Dominica', 'country_code' => 'DM', 'phonecode' => '1767', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Dominican Republic', 'country_code' => 'DO', 'phonecode' => '1809', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Ecuador', 'country_code' => 'EC', 'phonecode' => '593', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Egypt', 'country_code' => 'EG', 'phonecode' => '20', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'El Salvador', 'country_code' => 'SV', 'phonecode' => '503', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Equatorial Guinea', 'country_code' => 'GQ', 'phonecode' => '240', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Eritrea', 'country_code' => 'ER', 'phonecode' => '291', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Estonia', 'country_code' => 'EE', 'phonecode' => '372', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Ethiopia', 'country_code' => 'ET', 'phonecode' => '251', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Falkland Islands (Malvinas)', 'country_code' => 'FK', 'phonecode' => '500', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Faroe Islands', 'country_code' => 'FO', 'phonecode' => '298', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Fiji', 'country_code' => 'FJ', 'phonecode' => '679', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Finland', 'country_code' => 'FI', 'phonecode' => '358', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'France', 'country_code' => 'FR', 'phonecode' => '33', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'French Guiana', 'country_code' => 'GF', 'phonecode' => '594', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'French Polynesia', 'country_code' => 'PF', 'phonecode' => '689', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'French Southern Territories', 'country_code' => 'TF', 'phonecode' => '0', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Gabon', 'country_code' => 'GA', 'phonecode' => '241', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Gambia', 'country_code' => 'GM', 'phonecode' => '220', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Georgia', 'country_code' => 'GE', 'phonecode' => '995', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Germany', 'country_code' => 'DE', 'phonecode' => '49', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Ghana', 'country_code' => 'GH', 'phonecode' => '233', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Gibraltar', 'country_code' => 'GI', 'phonecode' => '350', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Greece', 'country_code' => 'GR', 'phonecode' => '30', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Greenland', 'country_code' => 'GL', 'phonecode' => '299', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Grenada', 'country_code' => 'GD', 'phonecode' => '1473', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Guadeloupe', 'country_code' => 'GP', 'phonecode' => '590', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Guam', 'country_code' => 'GU', 'phonecode' => '1671', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Guatemala', 'country_code' => 'GT', 'phonecode' => '502', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Guernsey', 'country_code' => 'GG', 'phonecode' => '44', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Guinea', 'country_code' => 'GN', 'phonecode' => '240', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Guinea-Bissau', 'country_code' => 'GW', 'phonecode' => '245', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Guyana', 'country_code' => 'GY', 'phonecode' => '592', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Haiti', 'country_code' => 'HT', 'phonecode' => '509', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Heard Island and McDonald Mcdonald Islands', 'country_code' => 'HM', 'phonecode' => '0', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Holy See (Vatican City State)', 'country_code' => 'VA', 'phonecode' => '39', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Honduras', 'country_code' => 'HN', 'phonecode' => '504', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Hong Kong', 'country_code' => 'HK', 'phonecode' => '852', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Hungary', 'country_code' => 'HU', 'phonecode' => '36', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Iceland', 'country_code' => 'IS', 'phonecode' => '354', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'India', 'country_code' => 'IN', 'phonecode' => '91', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Indonesia', 'country_code' => 'ID', 'phonecode' => '62', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Iran, Islamic Republic of', 'country_code' => 'IR', 'phonecode' => '98', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Iraq', 'country_code' => 'IQ', 'phonecode' => '964', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Ireland', 'country_code' => 'IE', 'phonecode' => '353', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Isle of Man', 'country_code' => 'IM', 'phonecode' => '44', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Israel', 'country_code' => 'IL', 'phonecode' => '972', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Italy', 'country_code' => 'IT', 'phonecode' => '39', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Jamaica', 'country_code' => 'JM', 'phonecode' => '1876', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Japan', 'country_code' => 'JP', 'phonecode' => '81', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Jersey', 'country_code' => 'JE', 'phonecode' => '44', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Jordan', 'country_code' => 'JO', 'phonecode' => '962', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Kazakhstan', 'country_code' => 'KZ', 'phonecode' => '7', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Kenya', 'country_code' => 'KE', 'phonecode' => '254', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Kiribati', 'country_code' => 'KI', 'phonecode' => '686', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Korea, Democratic People\'s Republic of', 'country_code' => 'KP', 'phonecode' => '850', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Korea, Republic of', 'country_code' => 'KR', 'phonecode' => '82', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Kuwait', 'country_code' => 'KW', 'phonecode' => '965', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Kyrgyzstan', 'country_code' => 'KG', 'phonecode' => '996', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Lao People\'s Democratic Republic', 'country_code' => 'LA', 'phonecode' => '856', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Latvia', 'country_code' => 'LV', 'phonecode' => '371', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Lebanon', 'country_code' => 'LB', 'phonecode' => '961', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Lesotho', 'country_code' => 'LS', 'phonecode' => '266', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Liberia', 'country_code' => 'LR', 'phonecode' => '231', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Libya', 'country_code' => 'LY', 'phonecode' => '218', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Liechtenstein', 'country_code' => 'LI', 'phonecode' => '423', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Lithuania', 'country_code' => 'LT', 'phonecode' => '370', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Luxembourg', 'country_code' => 'LU', 'phonecode' => '352', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Macao', 'country_code' => 'MO', 'phonecode' => '853', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Macedonia, the Former Yugoslav Republic of', 'country_code' => 'MK', 'phonecode' => '389', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Madagascar', 'country_code' => 'MG', 'phonecode' => '261', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Malawi', 'country_code' => 'MW', 'phonecode' => '265', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Malaysia', 'country_code' => 'MY', 'phonecode' => '60', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Maldives', 'country_code' => 'MV', 'phonecode' => '960', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Mali', 'country_code' => 'ML', 'phonecode' => '223', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Malta', 'country_code' => 'MT', 'phonecode' => '356', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Marshall Islands', 'country_code' => 'MH', 'phonecode' => '692', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Martinique', 'country_code' => 'MQ', 'phonecode' => '596', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Mauritania', 'country_code' => 'MR', 'phonecode' => '222', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Mauritius', 'country_code' => 'MU', 'phonecode' => '230', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Mayotte', 'country_code' => 'YT', 'phonecode' => '269', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Mexico', 'country_code' => 'MX', 'phonecode' => '52', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Micronesia, Federated States of', 'country_code' => 'FM', 'phonecode' => '691', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Moldova, Republic of', 'country_code' => 'MD', 'phonecode' => '373', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Monaco', 'country_code' => 'MC', 'phonecode' => '377', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Mongolia', 'country_code' => 'MN', 'phonecode' => '976', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Montenegro', 'country_code' => 'ME', 'phonecode' => '381', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Montserrat', 'country_code' => 'MS', 'phonecode' => '1664', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Morocco', 'country_code' => 'MA', 'phonecode' => '212', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Mozambique', 'country_code' => 'MZ', 'phonecode' => '258', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Myanmar', 'country_code' => 'MM', 'phonecode' => '95', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Namibia', 'country_code' => 'NA', 'phonecode' => '264', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Nauru', 'country_code' => 'NR', 'phonecode' => '674', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Nepal', 'country_code' => 'NP', 'phonecode' => '977', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Netherlands', 'country_code' => 'NL', 'phonecode' => '31', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'New Caledonia', 'country_code' => 'NC', 'phonecode' => '687', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'New Zealand', 'country_code' => 'NZ', 'phonecode' => '64', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Nicaragua', 'country_code' => 'NI', 'phonecode' => '505', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Niger', 'country_code' => 'NE', 'phonecode' => '227', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Nigeria', 'country_code' => 'NG', 'phonecode' => '234', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Niue', 'country_code' => 'NU', 'phonecode' => '683', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Norfolk Island', 'country_code' => 'NF', 'phonecode' => '672', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Northern Mariana Islands', 'country_code' => 'MP', 'phonecode' => '1670', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Norway', 'country_code' => 'NO', 'phonecode' => '47', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Oman', 'country_code' => 'OM', 'phonecode' => '968', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Pakistan', 'country_code' => 'PK', 'phonecode' => '92', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Palau', 'country_code' => 'PW', 'phonecode' => '680', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Palestine, State of', 'country_code' => 'PS', 'phonecode' => '', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Panama', 'country_code' => 'PA', 'phonecode' => '507', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Papua New Guinea', 'country_code' => 'PG', 'phonecode' => '675', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Paraguay', 'country_code' => 'PY', 'phonecode' => '595', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Peru', 'country_code' => 'PE', 'phonecode' => '51', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Philippines', 'country_code' => 'PH', 'phonecode' => '63', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Pitcairn', 'country_code' => 'PN', 'phonecode' => '0', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Poland', 'country_code' => 'PL', 'phonecode' => '48', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Portugal', 'country_code' => 'PT', 'phonecode' => '351', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Puerto Rico', 'country_code' => 'PR', 'phonecode' => '1787', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Qatar', 'country_code' => 'QA', 'phonecode' => '974', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Réunion', 'country_code' => 'RE', 'phonecode' => '262', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Romania', 'country_code' => 'RO', 'phonecode' => '40', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Russian Federation', 'country_code' => 'RU', 'phonecode' => '70', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Rwanda', 'country_code' => 'RW', 'phonecode' => '250', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Saint Barthélemy', 'country_code' => 'BL', 'phonecode' => '590', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'country_code' => 'SH', 'phonecode' => '290', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Saint Kitts and Nevis', 'country_code' => 'KN', 'phonecode' => '1869', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Saint Lucia', 'country_code' => 'LC', 'phonecode' => '1758', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Saint Martin (French part)', 'country_code' => 'MF', 'phonecode' => '590', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Saint Pierre and Miquelon', 'country_code' => 'PM', 'phonecode' => '508', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Saint Vincent and the Grenadines', 'country_code' => 'VC', 'phonecode' => '1784', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Samoa', 'country_code' => 'WS', 'phonecode' => '684', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'San Marino', 'country_code' => 'SM', 'phonecode' => '378', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Sao Tome and Principe', 'country_code' => 'ST', 'phonecode' => '239', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Saudi Arabia', 'country_code' => 'SA', 'phonecode' => '966', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Senegal', 'country_code' => 'SN', 'phonecode' => '221', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Serbia', 'country_code' => 'RS', 'phonecode' => '381', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Seychelles', 'country_code' => 'SC', 'phonecode' => '248', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Sierra Leone', 'country_code' => 'SL', 'phonecode' => '232', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Singapore', 'country_code' => 'SG', 'phonecode' => '65', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Sint Maarten (Dutch part)', 'country_code' => 'SX', 'phonecode' => '1', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Slovakia', 'country_code' => 'SK', 'phonecode' => '421', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Slovenia', 'country_code' => 'SI', 'phonecode' => '386', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Solomon Islands', 'country_code' => 'SB', 'phonecode' => '677', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Somalia', 'country_code' => 'SO', 'phonecode' => '252', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'South Africa', 'country_code' => 'ZA', 'phonecode' => '27', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'South Georgia and the South Sandwich Islands', 'country_code' => 'GS', 'phonecode' => '0', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'South Sudan', 'country_code' => 'SS', 'phonecode' => '211', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Spain', 'country_code' => 'ES', 'phonecode' => '34', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Sri Lanka', 'country_code' => 'LK', 'phonecode' => '94', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Sudan', 'country_code' => 'SD', 'phonecode' => '249', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Suriname', 'country_code' => 'SR', 'phonecode' => '597', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Svalbard and Jan Mayen', 'country_code' => 'SJ', 'phonecode' => '47', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Swaziland', 'country_code' => 'SZ', 'phonecode' => '268', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Sweden', 'country_code' => 'SE', 'phonecode' => '46', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Switzerland', 'country_code' => 'CH', 'phonecode' => '41', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Syrian Arab Republic', 'country_code' => 'SY', 'phonecode' => '963', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Taiwan', 'country_code' => 'TW', 'phonecode' => '886', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Tajikistan', 'country_code' => 'TJ', 'phonecode' => '992', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Tanzania, United Republic of', 'country_code' => 'TZ', 'phonecode' => '255', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Thailand', 'country_code' => 'TH', 'phonecode' => '66', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Timor-Leste', 'country_code' => 'TL', 'phonecode' => '670', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Togo', 'country_code' => 'TG', 'phonecode' => '228', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Tokelau', 'country_code' => 'TK', 'phonecode' => '690', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Tonga', 'country_code' => 'TO', 'phonecode' => '676', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Trinidad and Tobago', 'country_code' => 'TT', 'phonecode' => '1868', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Tunisia', 'country_code' => 'TN', 'phonecode' => '216', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Turkey', 'country_code' => 'TR', 'phonecode' => '90', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Turkmenistan', 'country_code' => 'TM', 'phonecode' => '7370', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Turks and Caicos Islands', 'country_code' => 'TC', 'phonecode' => '1649', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Tuvalu', 'country_code' => 'TV', 'phonecode' => '688', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Uganda', 'country_code' => 'UG', 'phonecode' => '256', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Ukraine', 'country_code' => 'UA', 'phonecode' => '380', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'United Arab Emirates', 'country_code' => 'AE', 'phonecode' => '971', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'United Kingdom', 'country_code' => 'GB', 'phonecode' => '44', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'United States', 'country_code' => 'US', 'phonecode' => '1', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'United States Minor Outlying Islands', 'country_code' => 'UM', 'phonecode' => '1', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Uruguay', 'country_code' => 'UY', 'phonecode' => '598', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Uzbekistan', 'country_code' => 'UZ', 'phonecode' => '998', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Vanuatu', 'country_code' => 'VU', 'phonecode' => '678', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Venezuela, Bolivarian Republic of', 'country_code' => 'VE', 'phonecode' => '58', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Viet Nam', 'country_code' => 'VN', 'phonecode' => '84', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Virgin Islands, British', 'country_code' => 'VG', 'phonecode' => '1284', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Virgin Islands, U.S.', 'country_code' => 'VI', 'phonecode' => '1340', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Wallis and Futuna', 'country_code' => 'WF', 'phonecode' => '681', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Western Sahara', 'country_code' => 'EH', 'phonecode' => '212', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Yemen', 'country_code' => 'YE', 'phonecode' => '967', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Zambia', 'country_code' => 'ZM', 'phonecode' => '260', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'Zimbabwe', 'country_code' => 'ZW', 'phonecode' => '263', 'active' => '1', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ];

            DB::table('countries')->insert($countries);
        }
        else
        {
            echo "\e[31mTable is not empty, therefore NOT ";
        }
    }
}
