<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class PermissionScreensSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if(DB::table('permission_screens')->get()->count() == 0)
        {
        	$Roles = [
                [
                    'name' => 'Dashboard',
                    'create' => '',
                    'edit' => '',
                    'view' => '',
                    'other' => '',
                    'active' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Users',
                    'create' => 'users.create,users.store',
                    'edit' => 'users.edit,users.update',
                    'view' => 'users.index',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Modules',
                    'create' => 'modules.create,modules.store',
                    'edit' => 'modules.edit,modules.update',
                    'view' => 'modules.index,modules.show',
                    'other' => 'relation-table.fields',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Company',
                    'create' => 'companies.create,companies.store',
                    'edit' => 'companies.edit,companies.update',
                    'view' => 'companies.index,companies.show',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Settings',
                    'create' => 'settings-listing.create,settings-listing.store,terretory.create,terretory.store,grades.create,grades.store',
                    'edit' => 'settings-listing.edit,settings-listing.update,terretory.edit,terretory.update,grades.edit,grades.update',
                    'view' => 'settings-listing.index,settings-listing.show,terretory.index,terretory.show,grades.index,grades.show',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Departments',
                    'create' => 'departments.create,departments.store',
                    'edit' => 'departments.edit,departments.update',
                    'view' => 'departments.index,departments.show',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Warehouses',
                    'create' => 'warehouses.create,warehouses.store',
                    'edit' => 'warehouses.edit,warehouses.update',
                    'view' => 'warehouses.index,warehouses.show',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Stock',
                    'create' => 'stocks.create,stocks.store',
                    'edit' => 'stocks.edit,stocks.update',
                    'view' => 'stocks.index,stocks.show',
                    'other' => 'stock.item.units',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Account Groups',
                    'create' => 'groups.create,groups.store',
                    'edit' => 'groups.edit,groups.update',
                    'view' => 'masters.account,groups.index,groups.show',
                    'other' => 'account.groups-type',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Sales Ledger',
                    'create' => 'sales.create,sales.store',
                    'edit' => 'sales.edit,sales.update',
                    'view' => 'masters.account,masters.ledger,sales.index,sales.show',
                    'other' => 'sales.delete_consignee_address',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Purchase Ledger',
                    'create' => 'purchase.create,purchase.store',
                    'edit' => 'purchase.edit,purchase.update',
                    'view' => 'masters.account,masters.ledger,purchase.index,purchase.show',
                    'other' => 'purchase.delete_consignee_address',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'General Ledger',
                    'create' => 'general.create,general.store',
                    'edit' => 'general.edit,general.update',
                    'view' => 'masters.account,masters.ledger,general.index,general.show',
                    'other' => 'general.delete_consignee_address',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Customer Groups',
                    'create' => 'customer-groups.create,customer-groups.store',
                    'edit' => 'customer-groups.edit,customer-groups.update',
                    'view' => 'masters.account,customer-groups.index,customer-groups.show',
                    'other' => 'supplier-groups.groups-type',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Supplier Groups',
                    'create' => 'supplier-groups.create,supplier-groups.store',
                    'edit' => 'supplier-groups.edit,supplier-groups.update',
                    'view' => 'masters.account,supplier-groups.index,supplier-groups.show',
                    'other' => 'supplier-groups.groups-type',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Stock Items',
                    'create' => 'stock-items.create,stock-items.store',
                    'edit' => 'stock-items.edit,stock-items.update',
                    'view' => 'inventory.index,stock-items.index,stock-items.show',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Stock Groups',
                    'create' => 'stock-groups.create,stock-groups.store',
                    'edit' => 'stock-groups.edit,stock-groups.update',
                    'view' => 'inventory.index,stock-groups.index,stock-groups.show',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Unit',
                    'create' => 'units.create,units.store',
                    'edit' => 'units.edit,units.update',
                    'view' => 'inventory.index,units.index,units.show',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Stock Categories',
                    'create' => 'stock-categories.create,stock-categories.store',
                    'edit' => 'stock-categories.edit,stock-categories.update',
                    'view' => 'inventory.index,stock-categories.index,stock-categories.show',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'BOM',
                    'create' => 'bom.create,bom.store',
                    'edit' => 'bom.edit,bom.update',
                    'view' => 'inventory.index,bom.index,bom.show',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Batches',
                    'create' => 'batches.create,batches.store',
                    'edit' => 'batches.edit,batches.update',
                    'view' => 'inventory.index,batches.index,batches.show',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'QC Tests',
                    'create' => 'qc-tests.create,qc-tests.store',
                    'edit' => 'qc-tests.edit,qc-tests.update',
                    'view' => 'qc-tests.index,qc-tests.show',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Transporters',
                    'create' => 'transporter.create,transporter.store',
                    'edit' => 'transporter.edit,transporter.update',
                    'view' => 'transporter.index,transporter.show',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Materials',
                    'create' => 'materials.create,materials.store',
                    'edit' => 'materials.edit,materials.update',
                    'view' => 'transactions.purchase,materials.index,materials.show',
                    'other' => 'materials.getUnitFronItemId,material.item_by_id,material.item_by_pack_code',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Purchase Orders',
                    'create' => 'purchase-order.create,purchase-order.store',
                    'edit' => 'purchase-order.edit,purchase-order.update',
                    'view' => 'transactions.purchase,purchase-order.index,purchase-order.show',
                    'other' => 'purchase.supplier-details,purchase.stock-details',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Purchase Receipts',
                    'create' => 'purchase-receipt.create,purchase-receipt.store',
                    'edit' => 'purchase-receipt.edit,purchase-receipt.update',
                    'view' => 'transactions.purchase,purchase-receipt.index,purchase-receipt.show',
                    'other' => 'purchase.poitems-details',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Purchase Invoice',
                    'create' => 'purchase-invoice.create,purchase-invoice.store',
                    'edit' => 'purchase-invoice.edit,purchase-invoice.update',
                    'view' => 'transactions.purchase,purchase-invoice.index,purchase-invoice.show',
                    'other' => 'purchase.stock-details',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Purchase Returns',
                    'create' => 'purchase-return.create,purchase-return.store',
                    'edit' => 'purchase-return.edit,purchase-return.update',
                    'view' => 'transactions.purchase,purchase-return.index,purchase-return.show',
                    'other' => 'purchase.stock-details',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'QC Report',
                    'create' => 'qc-report.create,qc-report.store',
                    'edit' => 'qc-report.edit,qc-report.update',
                    'view' => 'transactions.purchase,qc-report.index,qc-report.show',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Quotations',
                    'create' => 'quotation.create,quotation.store',
                    'edit' => 'quotation.edit,quotation.update',
                    'view' => 'transactions.sales,quotation.index,quotation.show',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Sales Orders',
                    'create' => 'sales-order.create,sales-order.store',
                    'edit' => 'sales-order.edit,sales-order.update',
                    'view' => 'transactions.sales,sales-order.index,sales-order.show',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Delivery Note',
                    'create' => 'delivery-note.create, delivery-note.store',
                    'edit' => 'delivery-note.edit,delivery-note.update',
                    'view' => 'transactions.sales,delivery-note.index,delivery-note.show',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Sales Invoice',
                    'create' => 'sales-invoice.create, sales-invoice.store',
                    'edit' => 'sales-invoice.edit,sales-invoice.update',
                    'view' => 'transactions.sales,sales-invoice.index,sales-invoice.show',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Sales Return',
                    'create' => 'sales-return.create, sales-return.store',
                    'edit' => 'sales-return.edit,sales-return.update',
                    'view' => 'transactions.sales,sales-return.index,sales-return.show',
                    'other' => '',
                    'active' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ]
            ];

            DB::table('permission_screens')->insert($Roles);
        }
        else
        {
            echo "\e[31mTable is not empty, therefore NOT ";
        }
    }
}
